server:
  port: 8011
spring:
  application:  #当前服务注册在Eureka Server 上的名称
    name: provider
  datasource:
             type: org.springframework.jdbc.datasource.DriverManagerDataSource
             url: jdbc:mysql:///student?serverTimezone=UTC
             username: root
             password: root
eureka:
  client:
    service-url:  #注册中心的访问地址
      defaultZone: http://localhost:8761/eureka/
  instance:  #是否将当前服务的IP注册到Eureka Server
    prefer-ip-address: true
#mapper映射
#mybatis:
#  mapper-locations: classpath*:/mapper/*.xml