server:
  port: 8761
eureka:
  client:
    register-with-eureka: false #是否将当前的Eureka Server服务作为客户端进行注册。
    fetch-registry: false  #是否获取其他Eureka Service 服务的数据
    service-url:  #注册中心访问地址
       defaultZone: http://localhost:8761/eureka/
spring:
      datasource:
           type: org.springframework.jdbc.datasource.DriverManagerDataSource
           url: jdbc:mysql:///student?serverTimezone=UTC
           username: root
           password: root