server:
  port: 8020
spring:
  application:
    name: consumer
  datasource:
    type: org.springframework.jdbc.datasource.DriverManagerDataSource
    url: jdbc:mysql:///student?serverTimezone=UTC
    username: root
    password: root
eureka:
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

