server:
  port: 8030
spring:
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true
  datasource:
      type: org.springframework.jdbc.datasource.DriverManagerDataSource
      url: jdbc:mysql:///student?serverTimezone=UTC
      username: root
      password: root
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes: #给服务提供者provider设置映射
    provider: /p/**

