server:
  port: 8762
spring:
  application:
    name: nativeconfigserver
  datasource:
           type: org.springframework.jdbc.datasource.DriverManagerDataSource
           url: jdbc:mysql:///student?serverTimezone=UTC
           username: root
           password: root
  profiles: #配置文件的获取方式
    active: native
  cloud:  #本地配置文件存放路径
    config:
      server:
        native:
          search-locations: classpath:/shared