spring:
      datasource:
           type: org.springframework.jdbc.datasource.DriverManagerDataSource
           url: jdbc:mysql:///student?serverTimezone=UTC
           username: root
           password: root