server:
  port: 8050
spring:
  application:
    name: feign
  datasource:
      type: org.springframework.jdbc.datasource.DriverManagerDataSource
      url: jdbc:mysql:///student?serverTimezone=UTC
      username: root
      password: root
eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
feign:
  hystrix: #是否开启熔断器
    enabled: true

