spring:
  application:
    name: hystrix
  datasource:
          type: org.springframework.jdbc.datasource.DriverManagerDataSource
          url: jdbc:mysql:///student?serverTimezone=UTC
          username: root
          password: root
server:
  port: 8060
eureka:
  client:
    service-url:
      defaulZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: 'hystrix.stream'
